BUG: Only delocate the platform wheels
The `itk` meta wheel does not have native binaries, its file name is
`itk-*`. All the platform wheels are `itk_*`.

To address:

Traceback (most recent call last):
  File "/Users/svc-dashboard/D/P/ITKPythonPackage/scripts/../venvs/3.10/bin/delocate-wheel", line 8, in <module>
    sys.exit(main())
  File "/Users/svc-dashboard/D/P/ITKPythonPackage/venvs/3.10/lib/python3.10/site-packages/delocate/cmd/delocate_wheel.py", line 110, in main
    copied = delocate_wheel(
  File "/Users/svc-dashboard/D/P/ITKPythonPackage/venvs/3.10/lib/python3.10/site-packages/delocate/delocating.py", line 1004, in delocate_wheel
    out_wheel_fixed = _check_and_update_wheel_name(
  File "/Users/svc-dashboard/D/P/ITKPythonPackage/venvs/3.10/lib/python3.10/site-packages/delocate/delocating.py", line 831, in _check_and_update_wheel_name
    new_name, problematic_files = _calculate_minimum_wheel_name(
  File "/Users/svc-dashboard/D/P/ITKPythonPackage/venvs/3.10/lib/python3.10/site-packages/delocate/delocating.py", line 798, in _calculate_minimum_wheel_name
    raise DelocationError(
delocate.libsana.DelocationError: Failed to find any binary with the required architecture: 'x86_64'