macpython: brew install doxygen only when not installed
Addresses:

  + brew install doxygen
  Error: doxygen 1.8.13_1 is already installed
  To upgrade to 1.8.14, run `brew upgrade doxygen`