scripts: Use check_call instead of check_output in Windows script
Work around

  error: [WinError 5] Access is denied:

a known issue with Python on Windows:

  https://stackoverflow.com/questions/26091530/permissionerror-winerror-5-access-is-denied-python-using-moviepy-to-write-gif

occuring in the ITKTotalVariation filter.